export const BALANCE_VERSION = 1 as const;

export const balanceV1 = {
  version: BALANCE_VERSION,
  startingResources: {
    energy: 250,
    metal: 150,
  },
  world: {
    slug: "ashfall-01",
    name: "Ashfall-01",
    initialWidth: 2048,
    initialHeight: 2048,
    chunkSize: 32,
    activeSpawnRegionSize: 512,
    generationVersion: 1,
  },
  spawn: {
    baseExclusionRadius: 12,
    attemptLimit: 40,
  },
  terrain: {
    phase1BlockedPercent: 8,
  },
  movement: {
    minIntervalMs: 80,
    maxCommandsPerMinute: 300,
    viewportRadius: 5,
    maxChunkRadius: 1,
  },
  economy: {
    passive: {
      energyPerHour: 12,
      metalPerHour: 6,
      energyCap: 800,
      metalCap: 2200,
    },
    nodes: {
      energyPerThousandTiles: 18,
      metalPerThousandTiles: 10,
      energyYield: 30,
      metalYield: 18,
      collectChebyshevRange: 1,
    },
    upgrades: {
      base: {
        metalCost: 80,
        metalCostByFromLevel: {
          1: 80,
          2: 250,
          3: 650,
          4: 1600,
        },
        maxLevel: 5,
        extraEnergyPerHourPerLevel: 4,
        extraMetalPerHourPerLevel: 2,
      },
      storage: {
        maxLevel: 5,
        metalCostByFromLevel: {
          1: 60,
          2: 160,
          3: 420,
          4: 1100,
        },
        energyCapByLevel: {
          1: 800,
          2: 1400,
          3: 2400,
          4: 4000,
          5: 6500,
        },
        metalCapByLevel: {
          1: 2200,
          2: 3800,
          3: 6500,
          4: 11000,
          5: 18000,
        },
      },
    },
    caves: {
      perThousandTiles: 5,
      collectChebyshevRange: 1,
      starterTier: 1,
      energyCostByTier: {
        1: 35,
        2: 55,
        3: 80,
        4: 110,
        5: 150,
      },
    },
    tools: {
      maxTier: 5,
      bonusBpsByTier: {
        1: 1000,
        2: 2200,
        3: 3800,
        4: 6000,
        5: 9000,
      },
    },
  },
  troops: {
    startingDefense: 2,
    startingOffense: 2,
    offenseAttack: 10,
    defenseDefense: 10,
    cavePowerPerTier: 10,
    maxPerType: 20,
    recruitMetalCost: {
      OFFENSE: 40,
      DEFENSE: 35,
    },
  },
  combat: {
    varianceMinBps: 8500,
    varianceMaxBps: 11500,
    baseDefenseModifierBps: 10300,
    caveDefenseUnitsPerTier: 1,
  },
  pvp: {
    newPlayerProtectionMs: 72 * 3_600_000,
    repeatTargetCooldownMs: 8 * 3_600_000,
    raidChebyshevRange: 1,
    raidEnergyCost: 40,
    lootBps: 1200,
    energyLootCap: 120,
    metalLootCap: 180,
    minDefensePowerUnits: 1,
  },
  bots: {
    maxActive: 40,
    minTickIntervalMs: 20_000,
    maxBotsPerTick: 12,
    difficulties: {
      SCOUT: {
        label: "Scout",
        actionsPerTick: 1,
        exploreRadius: 6,
        targetDefense: 4,
        targetOffense: 2,
        raidChanceBps: 1200,
        caveChanceBps: 2800,
        upgradeChanceBps: 2800,
        maxDistanceFromBase: 8,
      },
      RAIDER: {
        label: "Raider",
        actionsPerTick: 2,
        exploreRadius: 10,
        targetDefense: 6,
        targetOffense: 8,
        raidChanceBps: 5600,
        caveChanceBps: 5200,
        upgradeChanceBps: 4800,
        maxDistanceFromBase: 14,
      },
      WARLORD: {
        label: "Warlord",
        actionsPerTick: 3,
        exploreRadius: 16,
        targetDefense: 12,
        targetOffense: 14,
        raidChanceBps: 8200,
        caveChanceBps: 7000,
        upgradeChanceBps: 7800,
        maxDistanceFromBase: 22,
      },
    },
  },
} as const;

export type BalanceV1 = typeof balanceV1;
